
client_config_backend: file
client_config:
    client_id: 651923281605-3aj6v67rpjivocssl94u1hl9eqslcv41.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive